OPTION(BUILD_DEBIAN11 "Build for Debian 11 (Bullseye) ARM32" OFF)

SET(CMAKE_SYSTEM_NAME Linux)
SET(CMAKE_SYSTEM_VERSION 1)

if (BUILD_DEBIAN11)
    set(CMAKE_C_COMPILER   /usr/bin/arm-linux-gnueabihf-gcc-10)
    set(CMAKE_CXX_COMPILER /usr/bin/arm-linux-gnueabihf-g++-10)
else()
    SET(CMAKE_C_COMPILER arm-linux-gnueabihf-gcc)
    SET(CMAKE_CXX_COMPILER arm-linux-gnueabihf-g++)
endif()

SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
